repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types_or: [python, pyi]
        require_serial: true
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
    -   id: mypy
        name: mypy
        entry: mypy
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        language: system
        types_or: [python, pyi]
        require_serial: true
    -   id: isort
        name: isort
        entry: isort
        args: ["--profile", "black"]
        language: system
        types_or: [cython, pyi, python]
        require_serial: true
