version: '3.5'
services:

  zookeeper:
    container_name: ${FORWARDER_ZOOKEEPER_CONTAINER_NAME:-zookeeper}
    hostname: ${FORWARDER_ZOOKEEPER_CONTAINER_NAME:-zookeeper}
    image: confluentinc/cp-zookeeper:7.2.1
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - frontend

  kafka1:
    container_name: ${FORWARDER_KAFKA_CONTAINER_NAME:-kafka1}
    hostname: ${FORWARDER_KAFKA_CONTAINER_NAME:-kafka1}
    image: confluentinc/cp-server:7.2.1
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9099:9099"
    networks:
      - frontend
    environment:
      KAFKA_ZOOKEEPER_CONNECT: ${FORWARDER_ZOOKEEPER_CONTAINER_NAME:-zookeeper}:2181
      KAFKA_BROKER_ID: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      ## listeners
      KAFKA_LISTENERS: 'BROKERS://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'BROKERS://${FORWARDER_KAFKA_CONTAINER_NAME:-kafka1}:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'BROKERS:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKERS

  simpleioc:
    container_name: ${FORWARDER_SIMPLEIOC_CONTAINER_NAME:-simpleioc}
    image: registry.esss.lu.se/ecdc/ess-dmsc/docker-softioc:latest
    tty: true
    networks:
      - frontend

  forwarder:
    container_name: ${FORWARDER_FORWARDER_CONTAINER_NAME:-forwarder}
    image: registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-build-node:latest
    depends_on:
      - kafka1
      - simpleioc
    tty: true
    networks:
      - frontend
    volumes:
    - ./shared_volume:/shared_source:rw

networks:
  frontend:
